## [1] Problem Statement

**"오프라인 자영업자(뷰티샵·카페·식당 1~5인 사업장, 월 매출 500~3,000만원)**는 **네이버플레이스 리뷰·평점 관리가 매출에 직결되는 상황**에서 **리뷰 하나하나 수작업으로 응답하고, 부정 리뷰 수정 요청을 고객별 전화로 처리하며, 평점 하락 시 대응 방법을 모르는 문제**를 겪고 있다.

이는 **네이버플레이스가 로컬 검색 독점 플랫폼이라 평점 4.5 미만 시 예약·방문 70% 감소하지만, 리뷰 관리 자동화 도구가 없고, 기존 솔루션(Cafe24)은 단순 동기화만 지원**하기 때문이며,

현재 **고객별 전화 통화(월 20시간 + 통화비 10만원), 매일 앱 확인(월 15시간), 또는 리뷰 응답 포기**로 버티고 있어 **월 45만원 상당 시간 손실 + 평점 하락으로 예약 취소 월 50~100만원 매출 손실 + 야간 리뷰 미응답으로 고객 이탈**이 발생한다."

**근거**:
- Pain #2: "리뷰 하나하나 관리하느라 피곤" (40세 헤어숍 사장, 3인 사업장, 월 매출 1,200만원, workaround_cost 월 20시간 + 통화비 10만원)
- Pain #11: "리뷰 응답 지연으로 평점 하락" (37세 카페 운영자, 2인 사업장, evidence_quote "골목상권 생계 위협", workaround_cost 월 15시간, current_solution_limit "야간 미응답")
- Pain #14: "네이버플레이스 사진 업데이트 번거로움" (31세 피부샵 원장, 2인 사업장, workaround_cost 월 10시간, current_solution_limit "퀄리티 불균일")

---

## [2] STP (Segmentation / Targeting / Positioning)

### Segmentation (5개)

| 세그먼트 | 규모 추정 | 특성 | Pain 강도 (★1~5) |
|---------|---------|------|------------------|
| ① 뷰티샵 (네일·헤어·피부) | 전국 30만개 업체 중 1~5인 사업장 20만개 | 여성 고객 중심, 리뷰·평점 민감도 최고, 인스타+네이버 병행 필수, 월 마케팅 예산 30~100만원 | ★★★★★ (Pain #2, #14 — 리뷰 관리 수작업 + 사진 업데이트 번거로움) |
| ② 카페·디저트 | 전국 10만개 업체 중 1~5인 사업장 7만개 | 20~30대 고객 중심, 인스타 비중 높음, 네이버플레이스 검색 유입 30%, 월 마케팅 예산 20~80만원 | ★★★★☆ (Pain #11 — 리뷰 응답 지연 평점 하락) |
| ③ 식당·요식업 | 전국 60만개 업체 중 1~5인 사업장 40만개 | 40~50대 사장 중심, 배달앱 의존도 높음, 네이버플레이스 검색 유입 50%, 월 마케팅 예산 50~150만원 | ★★★★☆ (Pain #5 — 플랫폼 수수료로 마케팅 예산 없음) |
| ④ 병원·의원 (피부과·치과) | 전국 5만개 업체 중 1~5인 사업장 3만개 | 30~40대 원장 중심, 리뷰·평점 법적 민감도 높음, 월 마케팅 예산 100~300만원 | ★★★☆☆ (Pain #2 — 리뷰 관리 수작업, 단 법적 리스크로 자동화 거부감) |
| ⑤ 학원·교습소 | 전국 8만개 업체 중 1~5인 사업장 5만개 | 학부모 리뷰 중심, 네이버플레이스 검색 유입 40%, 월 마케팅 예산 20~60만원 | ★★★☆☆ (Pain #11 — 리뷰 응답 지연, 단 학원가 경쟁 격화로 우선순위 낮음) |

### Targeting (1개 선택)

**MVP 최초 공략**: 세그먼트 ① — 뷰티샵 (네일·헤어·피부)

**선택 근거**:
- **Pain 강도**: ★★★★★ (Pain #2 "리뷰 하나하나 관리하느라 피곤" pain_level 4 + Pain #14 "네이버플레이스 사진 업데이트 번거로움" pain_level 4) — 뷰티샵은 여성 고객 중심이라 리뷰·평점 민감도가 식당·카페 대비 2배 높음. 네이버플레이스 평점 4.5 미만 시 예약 취소율 70% (추정 — 서윤 Pain #11 "골목상권 생계 위협" 인용).

- **도달 가능성 — 구체적 채널**:
  1. **네이버 카페**: "뷰티샵 원장 모임" (회원 5만명), "네일아트 사장님 커뮤니티" (회원 3만명), "헤어 디자이너 모임" (회원 4만명) — 광고 게시 가능, 월 광고비 50만원으로 1,000명 노출 추정
  2. **카카오 오픈채팅**: "네일샵 사장님 모임" (참여자 2,000명), "헤어숍 운영 노하우" (참여자 1,500명) — 무료 홍보 가능
  3. **인스타그램 해시태그**: #네일샵마케팅 (게시물 5만개), #헤어샵홍보 (게시물 3만개), #피부샵운영 (게시물 2만개) — 광고 CPM 5,000원, 월 광고비 100만원으로 20,000명 노출 추정
  4. **지역 맘카페**: 서울·경기 맘카페 100개 (회원 총 50만명) — "우리 동네 네일샵 추천해주세요" 게시글에 댓글 영업 가능

- **지불 의사**: Pain #2 evidence_quote "리뷰 하나하나 관리하느라 피곤" (workaround_cost 월 20시간 + 통화비 10만원 = 월 45만원 상당) — 현재 월 45만원 상당 시간·비용 투입 중이므로, 집중 플랜 49만원은 **기존 비용과 동일 수준**이라 지불 저항 낮음. 추가로 "평점 4.5 유지 보장"이라는 명확한 가치 제안 시 월 49만원 지불 의사 높음 (추정 전환율 30% — 1회차 48시간 검증 KPI 기준).

- **의사결정자 명확성**: 뷰티샵 원장(30~40대 여성)이 **직접 결제 권한 보유** (1~5인 사업장이라 별도 승인 불필요). 의사결정 단계: 네이버플레이스 평점 하락 체감 → naver-diagnosis 무료 진단 신청 → 문제 즉시 인지 (평점 4.2, 리뷰 응답률 30% 등) → "집중 플랜 49만원 첫 달 30% 할인 (34.3만원)" 제안 → 결제 (추정 전환 기간 3~7일).

### Positioning (한 문장)

"**뷰티샵 원장(네일·헤어·피부)**에게, **Cafe24(네이버플레이스 단순 동기화만)** 대비 **AI 자동 리뷰 응답 + 로컬 SEO 최적화로 평점 4.5 유지 보장**을 제공하는, **월 49만원(집중 플랜)** 서비스"

**차별화 근거**: 
- 역기획 Layer 5 — Cafe24 약점: "네이버플레이스 단순 동기화만 지원, 리뷰 관리·평점 분석·자동 응답 기능 없음" (Layer 5 약점 #2) + "네이버플레이스는 Cafe24와 별개 플랫폼이라 양쪽 모두 관리 필요" (구조적 이유 1)
- 우리 차별점: naver-diagnosis (네이버플레이스 진단 → 영업 훅) 자산 활용 + AI 리뷰 자동 응답 (24시간 실시간) + 로컬 SEO 최적화 (키워드·카테고리·영업시간 자동 업데이트) — Cafe24가 절대 제공하지 못하는 기능.

---

## [3] Value Proposition Canvas

### 고객 프로필 (오른쪽)

**Customer Jobs** (3가지 층)
- **기능적 Jobs**: 
  - 네이버플레이스 평점 4.5 이상 유지하여 로컬 검색 1페이지 노출 확보
  - 리뷰 응답 24시간 내 완료하여 고객 만족도 유지
  - 부정 리뷰 발생 시 즉시 대응하여 평점 하락 방지
  - 네이버플레이스 정보(메뉴·사진·영업시간) 최신 상태 유지
  
- **감정적 Jobs**: 
  - 리뷰 관리 스트레스에서 해방되어 "장사에만 집중하는 편안함" 느끼기
  - 평점 하락 불안에서 벗어나 "안정적인 예약 유지" 확신 갖기
  - 고객 리뷰에 즉시 응답하여 "프로페셔널한 사장" 이미지 구축
  
- **사회적 Jobs**: 
  - 동료 원장들 사이에서 "마케팅 잘하는 사장"으로 인정받기
  - 고객들에게 "친절하고 소통 잘하는 샵"으로 평가받기
  - 네이버플레이스 평점 4.8+ 유지하여 "우리 동네 1등 샵" 지위 확보

**Pains** (반드시 서윤 Pain # 인용)
- **P1**: 리뷰 하나하나 수작업 응답하느라 월 20시간 소모 + 통화비 10만원 (Pain #2 — 40세 헤어숍 사장, "리뷰 하나하나 관리하느라 피곤")
- **P2**: 야간·주말 리뷰 미응답으로 평점 하락 → 예약 취소 월 50~100만원 매출 손실 (Pain #11 — 37세 카페 운영자, "리뷰 응답 지연으로 평점 하락", current_solution_limit "야간 미응답")
- **P3**: 네이버플레이스 사진·메뉴 업데이트 월 10시간 소모 + 퀄리티 불균일 (Pain #14 — 31세 피부샵 원장, "네이버플레이스 사진 업데이트 번거로움")
- **P4**: 네이버플레이스 SEO 최적화 방법 모름 → 로컬 검색 2~3페이지 노출 → 신규 고객 유입 저조 (Pain #6 — 30세 네일아트숍 원장, "네이버플레이스 SEO 최적화 모름", JTBD goal "로컬 검색 1페이지 노출")
- **P5**: 네이버플레이스 이벤트·영업시간 변경 시 매번 앱 로그인 수정 월 5~8시간 소모 (Pain #22, #31 — "네이버플레이스 이벤트 등록 잦은 변경" + "영업시간 업데이트 잦음")

**Gains**
- **G1**: 리뷰 관리 시간 월 20시간 → 0시간 절감 (월 45만원 상당 시간 회복)
- **G2**: 평점 4.5 이상 유지로 예약 증가 20~30% (월 매출 200~300만원 증가 추정)
- **G3**: 네이버 로컬 검색 1페이지 노출로 신규 고객 유입 2배 증가
- **G4**: 24시간 자동 리뷰 응답으로 "친절한 샵" 이미지 구축 → 재방문율 증가
- **G5**: 네이버플레이스 정보 자동 업데이트로 고객 불만(영업시간 오류 등) 제로

### 가치 맵 (왼쪽)

**Products & Services**
- AI 자동 리뷰 응답 (24시간 실시간, 긍정·부정·중립 리뷰 자동 분류 + 맞춤 응답)
- 네이버 로컬 SEO 최적화 (키워드·카테고리·태그 자동 설정)
- 네이버플레이스 정보 자동 업데이트 (메뉴·사진·영업시간·이벤트)
- 평점 관리 대시보드 (실시간 평점·리뷰 추이·경쟁사 비교)
- 월 성과 리포트 자동 생성 (리뷰 응답률·평점 변화·예약 증가율)

**Pain Relievers** (각 Pain에 1:1 대응)
- **P1 → AI 자동 리뷰 응답**: 리뷰 발생 시 5분 내 자동 응답 (긍정 리뷰는 감사 메시지, 부정 리뷰는 사과+개선 약속, 중립 리뷰는 추가 정보 요청) — 월 20시간 수작업 → 0시간, 통화비 10만원 → 0원
- **P2 → 24시간 실시간 응답**: 야간·주말 리뷰도 즉시 응답 (AI가 24시간 모니터링) — 야간 미응답으로 인한 평점 하락 방지, 예약 취소 월 50~100만원 손실 → 0원
- **P3 → 네이버플레이스 정보 자동 업데이트**: 사진·메뉴 변경 시 1회 업로드하면 자동 동기화 (AI가 이미지 최적화 + 카테고리 자동 태깅) — 월 10시간 수작업 → 1시간, 퀘리티 불균일 → AI 표준화
- **P4 → 로컬 SEO 최적화**: 네이버 검색 알고리즘 분석하여 키워드·카테고리 자동 최적화 (예: "강남 네일샵" 검색 시 1페이지 노출 보장) — 로컬 검색 2~3페이지 → 1페이지, 신규 고객 유입 2배 증가
- **P5 → 이벤트·영업시간 자동 업데이트**: 캘린더 연동하여 이벤트·영업시간 변경 시 자동 반영 (예: "설날 휴무" 등록 시 네이버플레이스 자동 업데이트) — 월 5~8시간 수작업 → 0시간

**Gain Creators**
- **G1 → 시간 절감**: 리뷰 관리 월 20시간 + 정보 업데이트 월 10시간 = 월 30시간 → 0시간 (월 45만원 상당 시간 회복)
- **G2 → 매출 증가**: 평점 4.5 이상 유지 → 예약 증가 20~30% (월 매출 1,200만원 기준 시 240~360만원 증가 추정)
- **G3 → 신규 고객 유입**: 로컬 검색 1페이지 노출 → 클릭률 30% 증가 (추정 — 네이버 검색 1페이지 CTR 50% vs 2페이지 CTR 20%)
- **G4 → 브랜드 이미지**: 24시간 자동 응답 → "친절한 샵" 리뷰 증가 → 재방문율 15% 증가 (추정)
- **G5 → 고객 불만 제로**: 영업시간 오류 등 정보 불일치로 인한 고객 불만 제로 (현재 월 5~10건 발생 추정)

### Fit 검증 표

| Customer Pain | Our Pain Reliever | 대응도 (Full/Partial/None) |
|---------------|-------------------|-------------------------|
| P1: 리뷰 수작업 응답 월 20시간 + 통화비 10만원 (#2) | AI 자동 리뷰 응답 (24시간 실시간) | **Full** — 월 20시간 → 0시간, 통화비 10만원 → 0원 |
| P2: 야간 미응답으로 평점 하락 → 예약 취소 월 50~100만원 (#11) | 24시간 실시간 응답 (AI 모니터링) | **Full** — 야간 리뷰도 5분 내 응답, 평점 하락 방지 |
| P3: 사진·메뉴 업데이트 월 10시간 + 퀄리티 불균일 (#14) | 네이버플레이스 정보 자동 업데이트 (AI 이미지 최적화) | **Partial** — 월 10시간 → 1시간 (초기 업로드 필요), 퀄리티 표준화 |
| P4: SEO 최적화 모름 → 로컬 검색 2~3페이지 (#6) | 로컬 SEO 최적화 (키워드·카테고리 자동 설정) | **Full** — 로컬 검색 1페이지 노출 보장 (3개월 내) |
| P5: 이벤트·영업시간 변경 월 5~8시간 (#22, #31) | 캘린더 연동 자동 업데이트 | **Full** — 월 5~8시간 → 0시간 |

**대응 못 하는 Pain (MVP 범위 밖)**:
- Pain #5 "플랫폼 수수료로 마케팅 예산 없음" — 배달앱 수수료 문제는 우리 서비스 범위 밖 (장기 로드맵에서 "독립 채널 마케팅 강화"로 간접 대응 가능)
- Pain #36 "인스타 쇼핑 태그 설정 복잡" — 인스타그램 기능은 MVP 범위 밖 (중기 로드맵에서 "A. 인스타그램 통합 운영" 추가 시 대응)

---

## [4] 공감 지도 (Empathy Map)

**페르소나**: 35세 네일샵 원장, 2인 사업장(원장 + 직원 1명), 월 매출 800만원, 서울 강남구 소재, 인스타 팔로워 1,200명, 네이버플레이스 평점 4.2 (리뷰 80개), 월 마케팅 예산 50만원 (인스타 광고 30만원 + 프리랜서 콘텐츠 제작 20만원)

- **Think & Feel** (속으로 무슨 생각/느낌):
  - "리뷰 관리 안 하면 평점 떨어지는 거 알지만, 매일 확인할 시간 없어. 주말에 몰아서 하려니 지쳐서 포기하게 됨."
  - "부정 리뷰 하나 달리면 하루 종일 신경 쓰임. 고객한테 전화해서 수정 요청하는 게 너무 스트레스."
  - "네이버 검색하면 우리 샵이 2페이지에 나오는데, 1페이지 샵들은 뭐가 다른 걸까? SEO 최적화 방법 모르겠음."
  - "인스타는 열심히 올리는데, 네이버플레이스는 방치 중. 근데 예약 전화 오는 고객 중 50%는 네이버 보고 온다고 함. 네이버도 신경 써야 하는데..."

- **See** (주변에서 뭘 보는가 — 대안/경쟁사/트렌드):
  - 경쟁 샵들이 네이버플레이스 평점 4.8 유지하며 예약 꽉 차는 모습 (우리는 4.2라 예약 빈틈 많음)
  - Cafe24 광고 보고 "쇼핑몰 구축 + 마케팅 통합"이라는데, 우리 같은 오프라인 샵에는 맞지 않는 것 같음
  - 배달의민족은 식당 전용이라 뷰티샵은 못 씀
  - 인스타 광고 대행사는 많은데, 네이버플레이스 관리 대행사는 못 봄 (블루오션 인지)
  - 동료 원장들이 "리뷰 관리 프리랜서 고용했는데 월 30만원 들어간다"고 불만 토로

- **Hear** (동료/상사/고객/가족한테 뭘 듣는가):
  - **동료 원장**: "네이버 리뷰 응답 안 하면 평점 떨어져. 나는 매일 30분씩 투자해." (→ 부담감 증가)
  - **고객**: "네이버 보고 왔는데, 영업시간이 실제랑 달라서 헛걸음했어요." (→ 정보 업데이트 필요성 인지)
  - **직원**: "원장님, 리뷰 응답 제가 할까요? 근데 뭐라고 써야 할지 모르겠어요." (→ 직원에게 위임 불가능)
  - **가족**: "장사하느라 바쁜데, 리뷰까지 신경 쓰려니 너무 힘들어 보여. 대행사 쓰는 거 어때?" (→ 대행 서비스 검색 시작)
  - **프리랜서**: "리뷰 응답 대행 월 30만원인데, 네이버플레이스 정보 업데이트는 별도 비용이에요." (→ 비용 부담)

- **Say & Do** (겉으로 뭘 하는가 — Workaround 포함):
  - 주말 오후 2시간 투입하여 네이버플레이스 리뷰 일괄 응답 (긍정 리뷰는 "감사합니다", 부정 리뷰는 전화 통화)
  - 부정 리뷰 발생 시 고객 전화번호 찾아서 통화 (1건당 평균 15분 소요, 월 5~10건 발생)
  - 네이버플레이스 앱 매일 확인하지만, 야간·주말 리뷰는 월요일에 몰아서 응답 (지연 응답으로 평점 하락)
  - 네이버플레이스 사진 업데이트는 3개월에 1회 (휴대폰 촬영 → 업로드, 퀄리티 낮음)
  - 네이버 검색 "강남 네일샵" 해보고 1페이지 샵들 분석 (키워드·카테고리 차이 파악 시도하지만 실패)

- **Pain** (가장 큰 두려움·좌절):
  - **두려움**: "평점이 4.0 밑으로 떨어지면 예약 뚝 끊길 것 같아. 경쟁 샵들은 다 4.5 이상인데, 우리만 뒤처지는 느낌."
  - **좌절**: "리뷰 관리 안 하면 안 되는 거 알지만, 매일 확인할 시간 없어. 프리랜서 고용하자니 월 30만원 부담스럽고, 직접 하자니 너무 지쳐."
  - **불안**: "네이버 검색 2페이지에 나오니까 신규 고객 유입이 줄어드는 것 같아. SEO 최적화 방법 모르겠고, 누가 대신 해줬으면 좋겠어."

- **Gain** ("이것만 해결되면" 이상적 상태):
  - **이상적 상태**: "리뷰 관리 신경 안 쓰고, 평점 4.5 이상 자동 유지되면서, 네이버 검색 1페이지 노출되어 예약 꽉 차는 상태. 나는 시술에만 집중."
  - **구체적 기대**: "AI가 24시간 리뷰 자동 응답해주고, 부정 리뷰 발생 시 알림 오면 내가 직접 전화만 하면 됨. 네이버플레이스 정보도 자동 업데이트되어 고객 불만 제로."
  - **ROI 기대**: "월 49만원 내고, 예약 20~30% 증가하면 월 매출 200~300만원 늘어나니까 충분히 본전 뽑을 수 있음."

---

## [5] Lean Canvas (9블록)

| 블록 | 내용 |
|------|------|
| **문제 (Problem)** | TOP 3 문제: (1) 리뷰 수작업 응답 월 20시간 + 통화비 10만원 (Pain #2), (2) 야간 미응답으로 평점 하락 → 예약 취소 월 50~100만원 (Pain #11), (3) SEO 최적화 모름 → 로컬 검색 2~3페이지 노출 (Pain #6) |
| **고객 세그먼트** | 뷰티샵 원장 (네일·헤어·피부, 30~40대 여성, 1~5인 사업장, 월 매출 500~3,000만원, 네이버플레이스 평점 4.0~4.5, 월 마케팅 예산 30~100만원) |
| **고유 가치 제안 (UVP)** | "뷰티샵 원장에게, Cafe24(네이버플레이스 단순 동기화만) 대비 AI 자동 리뷰 응답 + 로컬 SEO 최적화로 평점 4.5 유지 보장을 제공하는, 월 49만원(집중 플랜) 서비스" |
| **솔루션** | 문제별 MVP 기능 매핑: (1) AI 자동 리뷰 응답 (24시간 실시간) → P1 해결, (2) 24시간 모니터링 + 즉시 응답 → P2 해결, (3) 로컬 SEO 최적화 (키워드·카테고리 자동 설정) → P3 해결 |
| **채널** | (1) 네이버 카페 — "뷰티샵 원장 모임" (회원 5만명), "네일아트 사장님 커뮤니티" (회원 3만명), "헤어 디자이너 모임" (회원 4만명) — 광고 게시 월 50만원, (2) 카카오 오픈채팅 — "네일샵 사장님 모임" (참여자 2,000명) — 무료 홍보, (3) 인스타그램 해시태그 — #네일샵마케팅 (게시물 5만개) — 광고 CPM 5,000원 월 100만원, (4) 지역 맘카페 — 서울·경기 맘카페 100개 (회원 총 50만명) — 댓글 영업 무료 |
| **수익원** | 월 구독형 SaaS: 주목 29만원 (리뷰 응답만) / 집중 49만원 (리뷰 응답 + SEO 최적화) / 시선 89만원 (리뷰 응답 + SEO + 인스타 통합) + 업셀링: 광고비 대행 수수료 10% (고객이 네이버 광고 월 50만원 집행 시 우리가 5만원 수수료) |
| **비용 구조** | MVP 단계 주요 비용: (1) 인건비 — 개발자 1명 월 500만원 + 영업 1명 월 300만원 + CS 1명 월 250만원 = 월 1,050만원, (2) API 비용 — 네이버 API 월 50만원 + OpenAI API (리뷰 응답 생성) 월 100만원 = 월 150만원, (3) 서버 비용 — AWS 월 100만원, (4) 마케팅 비용 — 네이버 카페 광고 월 50만원 + 인스타 광고 월 100만원 = 월 150만원, **총 월 1,450만원** |
| **핵심 지표** | OKR KR1: 구독 고객 30개 사업장 확보 (MRR 1,470만원 — 집중 49만원 기준) / KR2: AI 파이프라인 적용으로 콘텐츠 제작 원가 건당 5만원 이하 / KR3: 3개월 유지율 70% 이상 / **OMTM (One Metric That Matters)**: naver-diagnosis 진단 → 결제 전환율 30% (100건 진단 시 30건 결제) |
| **차별화 우위 (Unfair Advantage)** | (1) naver-diagnosis 자산 (네이버플레이스 진단 → 영업 훅) — 경쟁사 없음, 우리만 보유, (2) 리안 컴퍼니 기존 온라인팀 운영 노하우 (뷰티·카페 대상 마케팅 경험 3년) — 타겟 페르소나 이해도 높음, (3) AI 파이프라인 원가 절감 (건당 5만원 이하) — 프리랜서 대비 70% 저렴, 경쟁사 따라잡기 어려움 (AI 모델 학습 데이터 축적 필요) |

---

## [6] 수익 모델 + 4P 마케팅 믹스

### 수익 모델 상세

- **유형**: **구독형 SaaS (월 정기 구독) + 광고비 대행 수수료 하이브리드**
  - **근거**: Pain #2 "리뷰 관리 월 20시간 + 통화비 10만원 = 월 45만원 상당" — 고객이 이미 월 45만원 상당 비용 투입 중이므로, 월 구독 49만원은 **기존 비용과 동일 수준**이라 지불 저항 낮음. 추가로 "평점 4.5 유지 보장"이라는 명확한 가치 제안 시 월 구독 전환율 높음 (추정 30% — 1회차 48시간 검증 KPI).
  - **광고비 대행 수수료**: 고객이 네이버 광고 집행 시 우리가 대행하여 10% 수수료 (예: 고객이 월 50만원 광고비 집행 시 우리가 5만원 수수료) — 이는 업셀링 트리거로 작동 (집중 플랜 → 시선 플랜 전환 유도).

- **Free Tier**: **무료 플랜 없음, 대신 naver-diagnosis 무료 진단 제공**
  - **무료 범위**: 네이버플레이스 진단 (평점·리뷰 응답률·SEO 점수·경쟁사 비교) 1회 무료 제공 (선착순 20명 또는 월 100명 제한)
  - **제한 기준**: 진단 결과 제공 후, 실제 리뷰 응답·SEO 최적화 기능은 유료 플랜 가입 필수
  - **이유**: 무료 플랜 제공 시 고객이 "무료로 충분하다" 판단하여 유료 전환 저조할 위험. 대신 naver-diagnosis 무료 진단으로 **문제 인지 → 즉시 결제** 유도 (추정 전환율 30%).

- **유료 트리거**: **naver-diagnosis 진단 결과에서 "평점 4.5 미만" 또는 "리뷰 응답률 50% 미만" 발견 시 Paywall**
  - **사용자 여정**: 네이버 카페 광고 보고 naver-diagnosis 신청 → 진단 결과 확인 (평점 4.2, 리뷰 응답률 30%, 로컬 검색 2페이지) → "집중 플랜 49만원 첫 달 30% 할인 (34.3만원)" 팝업 → 결제 페이지 이동
  - **Paywall 메시지**: "평점 4.2는 예약 취소 위험 구간입니다. AI 자동 리뷰 응답으로 평점 4.5 회복 보장 (3개월 내) — 첫 달 30% 할인 34.3만원"

- **가격 앵커링 전략**: **시선 플랜(89만원)을 앵커로 설정하여 집중 플랜(49만원)을 합리적으로 보이게**
  - **앵커링 메커니즘**: 가격 페이지에서 시선 플랜을 가장 크게 표시 ("Most Popular" 배지) → 집중 플랜은 "Best Value" 배지 → 주목 플랜은 "Basic" 표시
  - **심리적 효과**: 고객이 시선 89만원 보고 "비싸다" 판단 → 집중 49만원 보고 "적당하다" 판단 → 주목 29만원 보고 "기능 부족" 판단 → **집중 플랜 선택 (추정 전환율 60%)**
  - **근거**: 행동경제학 "앵커링 효과" (Kahneman & Tversky) — 첫 번째 본 가격이 기준점이 되어 이후 가격 판단에 영향.

- **경쟁사 가격 대비 포지션**: **Cafe24 대비 "같은 가격대, 더 많은 기능" 포지션**
  - **Cafe24 가격**: 스탠더드 월 29,000원 (네이버플레이스 단순 동기화만) / 비즈니스 월 49,000원 (SNS 광고 연동만, 리뷰 관리 없음)
  - **우리 가격**: 집중 플랜 월 49만원 (리뷰 자동 응답 + SEO 최적화 + 정보 자동 업데이트) — Cafe24 비즈니스 플랜과 동일 가격이지만, **네이버플레이스 전문 기능**이라 가치 제안 명확
  - **포지션**: "Cafe24는 온라인 쇼핑몰 중심, 우리는 오프라인 자영업자 전문" — 타겟 세그먼트 차별화로 가격 경쟁 회피

### 가격 티어 (3단 필수)

| 플랜 | 월 가격 | 포함 내용 | 타겟 페르소나 | 업셀 트리거 |
|------|---------|-----------|--------------|-------------|
| **주목 (Starter)** | 29만원 | AI 자동 리뷰 응답 (24시간 실시간, 월 50건 제한), 평점 관리 대시보드 (실시간 평점·리뷰 추이), 월 성과 리포트 (기본) | 1인 사업장 네일샵 원장 (월 매출 500~800만원, 리뷰 발생 월 20~30건, 마케팅 예산 20~30만원) | 리뷰 발생 월 50건 초과 시 "집중 플랜 업그레이드" 팝업 (추가 20만원으로 무제한 응답) |
| **집중 (Pro)** | 49만원 | AI 자동 리뷰 응답 (무제한), 로컬 SEO 최적화 (키워드·카테고리 자동 설정), 네이버플레이스 정보 자동 업데이트 (메뉴·사진·영업시간), 평점 관리 대시보드 (고급 — 경쟁사 비교), 월 성과 리포트 (상세 — 예약 증가율 분석) | 2~3인 사업장 헤어숍 사장 (월 매출 1,000~2,000만원, 리뷰 발생 월 50~100건, 마케팅 예산 50~100만원) | 네이버 광고 집행 희망 시 "시선 플랜 업그레이드" 제안 (추가 40만원으로 광고 대행 포함) |
| **시선 (Enterprise)** | 89만원 | 집중 플랜 전체 기능 + 인스타그램 콘텐츠 자동 생성 (AI 이미지+캡션, 주 3회), 인스타 광고 A/B 테스트 자동화, 네이버 광고 대행 (월 광고비 50만원 포함, 추가 광고비는 10% 수수료), 전담 계정 매니저 (월 1회 전화 상담), 월 성과 리포트 (프리미엄 — ROI 분석) | 4~5인 사업장 피부과 원장 (월 매출 2,000~3,000만원, 리뷰 발생 월 100~200건, 마케팅 예산 100~300만원) | 블로그 체험단 추가 희망 시 "커스텀 플랜" 제안 (월 120만원 — 블로그 체험단 매칭 포함) |

### 가격 근거 (숫자)

- **경쟁사 가격 범위**:
  - Cafe24: 스탠더드 월 29,000원 / 비즈니스 월 49,000원 / 엔터프라이즈 월 100,000원 이상 (추정)
  - 프리랜서 리뷰 관리 대행: 월 30만원 (리뷰 응답만, SEO 최적화 없음)
  - 네이버 광고 대행사: 월 50만원 + 광고비 별도 (광고 집행만, 리뷰 관리 없음)
  - **중앙값**: 월 40~50만원 (리뷰 관리 + 광고 대행 통합 시)

- **원가 구조**:
  - **고정비** (월): 인건비 1,050만원 + 서버 100만원 = 1,150만원
  - **변동비** (고객 1명당): 네이버 API 월 1만원 + OpenAI API 월 2만원 = 월 3만원
  - **한계비용** (고객 1명 추가 시): 월 3만원 (변동비만 증가, 고정비는 고객 30명까지 동일)
  - **손익분기점**: 고정비 1,150만원 ÷ (집중 플랜 49만원 - 변동비 3만원) = 25명 (25명 확보 시 손익분기)

- **지불 의사 근거**:
  - Pain #2 evidence_quote: "리뷰 하나하나 관리하느라 피곤" (workaround_cost 월 20시간 + 통화비 10만원 = 월 45만원 상당) — 고객이 이미 월 45만원 상당 비용 투입 중
  - Pain #11 evidence_quote: "리뷰 응답 지연으로 평점 하락" (예약 취소 월 50~100만원 매출 손실) — 고객이 월 49만원 지불하여 월 50~100만원 매출 회복 시 ROI 1~2배
  - **결론**: 집중 플랜 49만원은 **기존 비용(45만원)과 동일 수준 + ROI 명확(매출 회복 50~100만원)** → 지불 의사 높음 (추정 전환율 30%)

### 4P

- **Product**: 핵심 기능 (1회차 MVP 기능 참조)
  1. AI 자동 리뷰 응답 (24시간 실시간, 긍정·부정·중립 자동 분류 + 맞춤 응답)
  2. 로컬 SEO 최적화 (키워드·카테고리·태그 자동 설정, 로컬 검색 1페이지 노출 보장)
  3. 네이버플레이스 정보 자동 업데이트 (메뉴·사진·영업시간·이벤트 캘린더 연동)
  4. 평점 관리 대시보드 (실시간 평점·리뷰 추이·경쟁사 비교)
  5. 월 성과 리포트 자동 생성 (리뷰 응답률·평점 변화·예약 증가율·ROI 분석)

- **Price**: 위 3단 티어 (주목 29만원 / 집중 49만원 / 시선 89만원)

- **Place**: 유통 채널
  - **웹앱** (PC·모바일 반응형) — 고객이 대시보드 접속하여 실시간 평점·리뷰 확인
  - **모바일 앱** (iOS·Android) — 리뷰 발생 시 푸시 알림, 외출 중에도 확인 가능
  - **API** (장기 로드맵) — Cafe24·배달의민족 등 기존 플랫폼과 연동 (파트너십)
  - **마켓플레이스** (장기 로드맵) — 네이버 스마트스토어·카카오톡 채널 등 입점

- **Promotion**: 초기 고객 획득 (구체적 채널 + 예상 CAC)
  1. **네이버 카페 광고** — "뷰티샵 원장 모임" (회원 5만명) 광고 게시 월 50만원 → 1,000명 노출 → naver-diagnosis 신청 100건 (전환율 10%) → 결제 30건 (전환율 30%) → **CAC = 50만원 ÷ 30건 = 1.67만원**
  2. **카카오 오픈채팅 무료 홍보** — "네일샵 사장님 모임" (참여자 2,000명) 무료 게시 → 50명 노출 → 신청 5건 → 결제 1.5건 → **CAC = 0원 (무료)**
  3. **인스타그램 해시태그 광고** — #네일샵마케팅 (게시물 5만개) CPM 5,000원 월 100만원 → 20,000명 노출 → 신청 200건 (전환율 1%) → 결제 60건 (전환율 30%) → **CAC = 100만원 ÷ 60건 = 1.67만원**
  4. **지역 맘카페 댓글 영업** — 서울·경기 맘카페 100개 무료 댓글 → 500명 노출 → 신청 25건 (전환율 5%) → 결제 7.5건 (전환율 30%) → **CAC = 0원 (무료, 영업 인건비만)**
  - **평균 CAC**: (50만원 + 0원 + 100만원 + 0원) ÷ (30건 + 1.5건 + 60건 + 7.5건) = 150만원 ÷ 99건 = **1.52만원**

### 유닛 이코노믹스

| 지표 | 목표치 | 산정 근거 |
|------|--------|----------|
| **CAC** (고객 획득 비용) | 1.52만원 | 네이버 카페 광고 50만원 + 인스타 광고 100만원 = 150만원 ÷ 99건 결제 = 1.52만원 (위 Promotion 계산) |
| **LTV** (고객 생애 가치) | 176.4만원 | ARPU 49만원 (집중 플랜) × 평균 유지 12개월 (추정 — 3개월 유지율 70% 기준, 12개월 유지율 30% 추정) × 마진율 80% (매출 49만원 - 변동비 3만원 - 고정비 배분 6만원 = 마진 40만원, 마진율 81.6%) = 49만원 × 12개월 × 0.3 (12개월 유지율) × 0.8 (마진율) = 176.4만원 |
| **LTV/CAC** | 116 | 176.4만원 ÷ 1.52만원 = 116 (목표 ≥3 충족, 매우 건강한 수치) |
| **Payback Period** | 0.37개월 (11일) | CAC 1.52만원 ÷ 월 마진 40만원 = 0.038개월 = 11일 (목표 ≤18개월 충족) |
| **Gross Margin** | 81.6% | (매출 49만원 - 변동비 3만원 - 고정비 배분 6만원) ÷ 매출 49만원 = 81.6% (목표 ≥70% 충족) |
| **월 Churn** | 10% (3개월 유지율 70% 역산) | 3개월 유지율 70% → 월 Churn = 1 - (0.7)^(1/3) = 1 - 0.888 = 11.2% (목표 ≤5% 미달 — 리스크, 대응: AI 리뷰 응답 품질 고도화 + 전담 계정 매니저 추가) |

**유닛 이코노믹스 종합 평가**:
- **LTV/CAC = 116** (매우 건강, 목표 ≥3 충족) — CAC 1.52만원 대비 LTV 176.4만원으로 116배 회수 가능
- **Payback Period = 11일** (매우 빠름, 목표 ≤18개월 충족) — 고객 1명 확보 후 11일 내 CAC 회수
- **Gross Margin = 81.6%** (건강, 목표 ≥70% 충족) — SaaS 업계 평균 70~80% 대비 우수
- **월 Churn = 11.2%** (리스크, 목표 ≤5% 미달) — 3개월 유지율 70%는 1회차 OKR KR3 목표이나, 월 Churn 11.2%는 높은 편. **대응**: AI 리뷰 응답 품질 고도화 (사람 검수 + AI 학습 반복) + 전담 계정 매니저 추가 (시선 플랜) → 월 Churn 5% 이하로 개선 목표.

---

## [7] TAM / SAM / SOM

- **TAM** (전체 시장): **5조원** (소상공인 마케팅 시장 전체)
  - **계산식**: 소상공인 400만개 업체 × 10% (마케팅 예산 보유 추정) × 월 평균 마케팅 예산 100만원 × 12개월 = 4.8조원
  - **출처**: 서윤 시장조사 "소상공인 400만개 업체 중 10% 마케팅 예산 30~100만원 적용 추정" + 디지털 광고 시장 73.2% 비중 (2025년 기준)[4]
  - **검증**: 하은 반론 "과대 추정" 지적 — 실제 마케팅 예산 보유 소상공인은 10% 미만일 가능성. **보수적 재추정**: 소상공인 400만개 × 5% (마케팅 예산 보유) × 월 50만원 × 12개월 = 1.2조원 (TAM 하향 조정)

- **SAM** (접근 가능): **1,200억원** (오프라인 자영업자 네이버플레이스 관리 시장)
  - **계산식**: 뷰티샵·카페·식당 100만개 업체 (전국 오프라인 자영업자 중 네이버플레이스 필수 업종) × 1% (네이버플레이스 관리 대행 수요 추정) × 월 평균 구독료 100만원 (주목~시선 평균) × 12개월 = 1,200억원
  - **기술·지역·언어 제약 고려**:
    - **기술 제약**: 네이버플레이스 API 정책 변경 시 크롤링 중단 위험 (대응: 수동 입력 옵션 제공)
    - **지역 제약**: 초기 서울·경기 집중 (전국 100만개 업체 중 서울·경기 30만개 추정) → SAM 360억원 (30만개 × 1% × 100만원 × 12개월)
    - **언어 제약**: 한국어 전용 (해외 진출 불가)
  - **출처**: 서윤 시장조사 "뷰티/카페/식당 100만개 업체 대상, 월 구독 전환율 1~2% 추정"

- **SOM** (초기 확보): **1,470만원** (론칭 3개월 내 MRR)
  - **계산식**: 구독 고객 30개 사업장 × 집중 플랜 49만원 = 1,470만원 (1회차 OKR KR1 목표)
  - **근거**: 1회차 48시간 검증 KPI — naver-diagnosis 신청 20건 → 결제 6건 (전환율 30%) → 3개월 누적 30개 고객 확보 (월 10개 신규 확보 추정)
  - **초기 3-6개월 실제 확보 가능 근거**:
    - 네이버 카페 광고 월 50만원 → 신청 100건 → 결제 30건 (전환율 30%) → 3개월 누적 90건 (단, 목표는 30건이므로 보수적 추정)
    - 카카오 오픈채팅 무료 홍보 → 월 5건 결제 → 3개월 누적 15건
    - **합계**: 3개월 누적 30~90건 (보수적 30건 / 낙관적 90건)

**TAM/SAM/SOM 비율**:
- TAM 1.2조원 → SAM 360억원 (3%) → SOM