## 📌 STEP 0: OKR 자동 도출

```
Objective: 토지 매입 전 인허가 리스크를 90% 제거하여 중소 시행사의 사업 실패율을 1/3로 낮춘다
KR1: 베타 출시 3개월 내 유료 파일럿 고객 15개사 확보 (월 구독 기준)
KR2: 인허가 승인 확률 예측 정확도 75% 이상 달성 (실제 승인/거절 결과 대조)
KR3: 사용자 1건당 분석 시간 기존 2주 → 48시간 이내 단축 (NPS 8점 이상)
```

---

## [1] 필터링 (돈이 되는 고통만)

### 1차: pain_level 4~5만 통과
| 구분 | 수량 | Pain Point # |
|------|------|--------------|
| Level 5 통과 | 7개 | #2, #5, #6, #8, #18, #21, #24, #27 |
| Level 4 통과 | 20개 | #1, #3, #4, #7, #9, #11, #13, #14, #16, #17, #19, #20, #22, #25, #26, #28, #29, #30 |
| Level 1~3 탈락 | 23개 | - |
| **통과 합계** | **27개** | |

### 2차: Workaround 관찰 (is_workaround_observed = true)
27개 통과 → **27개** 에서 workaround 관찰됨.

주요 workaround 유형 5개:
1. **외부 컨설턴트 고용** (Pain #2, #6, #13, #16, #21, #27) — 월 300~800만원
2. **엑셀 수작업 반복** (Pain #1, #4, #8, #9, #17, #20, #28) — 월 30~60시간
3. **변호사/법무법인 의뢰** (Pain #3, #22, #29) — 월 200~300만원
4. **공공 데이터 수동 다운로드** (Pain #7, #11, #15, #23) — 월 15~45시간
5. **현장 방문 물리적 확인** (Pain #14) — 월 100만원

### 3차: source_confidence 필터
source_confidence < 3 제외 → 최종 **23개** 통과.
(제외: #12, #13, #22, #25 — confidence 3 미만)

### 블루오션 플래그
pain_level 4~5 + competitor_url = "none (blue ocean)" 항목:

| Pain # | 제목 | Level |
|--------|------|-------|
| #1 | 비정형 데이터 처리 수작업 시간 지연 | 4 |
| #2 | 인허가 승인 확률 예측 어려움 | 5 |
| #4 | 개발 투자금 범위 산출 번거로움 | 4 |
| #5 | 부동산 정책 흐름 모니터링 수동 | 5 |
| #6 | 토지 가격 평가 과다 부담 | 4 |
| #14 | 기술적 타당성 현장답사 외 자동화 없음 | 4 |
| #17 | 토지가격 평가 배점 기준 수동 적용 | 4 |
| #18 | 상업용부동산 투자 양극화 판단 지연 | 5 |
| #20 | 프로젝트 파이낸싱 구조 분석 엑셀 의존 | 4 |
| #21 | 분양성 판단 물건·토지가격 적정성 수작업 | 5 |
| #24 | 공공 택지 토지가격 부담 공익성 저하 | 5 |
| #27 | 부동산 시장 침체 시 사업성 재평가 빈도 증가 | 5 |
| #28 | 현금흐름 분석 변수 변화 대응 느림 | 4 |
| #29 | 용도지역 판독 법률서 해석 어려움 | 5 |
| #30 | 투자 금액 범위 산출 금리 변동 미반영 | 4 |

---

## [2] TOP 5 클러스터링

통과한 23개를 JTBD 유사성 기준으로 5개 아이템으로 묶음:

| 아이템 | 관련 Pain # | 핵심 JTBD |
|--------|-------------|-----------|
| A. 인허가 승인 확률 예측 자동화 | #2, #21, #29 | 매입 전 리스크 제거 → 거절 손실 방지 |
| B. 투자 금액·수익성 자동 산출 | #4, #20, #28, #30 | 재무 타당성 즉시 판단 → 의사결정 속도 3배 |
| C. 특례법·용도지역 자동 판독 | #3, #29 | 법률 전문가 없이 개발 가능성 확인 |
| D. 부동산 정책 흐름 실시간 모니터링 | #5, #18, #27 | 정책 변화 대응 → 타이밍 포착 |
| E. 토지 가격 적정성 자동 평가 | #6, #17, #24 | 과다 매입 방지 → 사업성 확보 |

---

## [3] 가중치 스코어링 (TOP 5)

| 기준 (가중치) | A | B | C | D | E |
|--------------|---|---|---|---|---|
| Workaround 비용 (20%) | 9 (월 500만원 컨설팅 #2) | 8 (월 400만원 #20 + 50시간 #4) | 7 (월 300만원 변호사 #3) | 8 (월 200만원 인력 #5) | 9 (월 500만원 #24) |
| Payer 명확성 (15%) | 10 (대표 직접 결재 #2) | 9 (팀장→대표 승인 #4) | 8 (소장급 #3) | 7 (사업개발자→팀장 #5) | 9 (공공사업 팀장 #24) |
| Pre-sell 가능성 (15%) | 9 (거절 위험=즉시 pain) | 8 (예산 초과=명확 pain) | 7 (법률 해석=추상적) | 6 (정책 변화=간접 pain) | 8 (과다 매입=즉시 손실) |
| 경쟁 빈틈 (25%) | 10 (제너레잇 Layer 5 약점 #1) | 9 (제너레잇 약점 #2) | 8 (제너레잇 약점 #1 일부) | 7 (리치고 부분 제공) | 9 (blue ocean) |
| Build 난이도 (15%) | 6 (ML 모델+과거 데이터 필요) | 7 (금융 API 연동 복잡) | 5 (NLP+법률 DB 구축 어려움) | 8 (뉴스 크롤링+분류 상대적 쉬움) | 7 (감정평가 로직 복잡) |
| OKR 정합성 (10%) | 10 (KR2 정확도 직결) | 8 (KR3 시간 단축) | 7 (KR3 일부) | 6 (간접 기여) | 7 (KR1 고객 확보) |
| **종합 점수** | **8.95** | **8.25** | **7.05** | **7.15** | **8.35** |

**각 점수 산출 근거**:
- **A 종합 8.95**: Workaround 비용 9점 (Pain #2 월 500만원 컨설팅 직접 인용), Payer 10점 (대표급 직접 결재), 경쟁 빈틈 10점 (제너레잇 Layer 5 약점 #1 "승인 확률 예측 신뢰도 낮음" 직접 연결), Build 난이도 6점 (과거 인허가 데이터 300~500건 확보 필요 = 6개월 소요)
- **B 종합 8.25**: Workaround 비용 8점 (Pain #20 월 400만원 + Pain #4 월 50시간 = 약 200만원), 경쟁 빈틈 9점 (제너레잇 약점 #2 "금리 변동 미반영"), Build 난이도 7점 (한국은행 API + 부동산114 API 연동 = 3개월 가능하나 현금흐름 모델 복잡)
- **C 종합 7.05**: Build 난이도 5점 (NLP 모델 + 특례법 텍스트 DB 구축 = 1년 이상 소요), 경쟁 빈틈 8점 (제너레잇 약점 #1 일부 해당하나 법률 도메인은 별도)
- **D 종합 7.15**: 경쟁 빈틈 7점 (리치고가 부분 제공), Build 난이도 8점 (뉴스 크롤링 + 키워드 분류 = 상대적 쉬움)
- **E 종합 8.35**: Workaround 비용 9점 (Pain #24 월 500만원), Payer 9점 (공공사업 팀장 = 예산 권한), 경쟁 빈틈 9점 (blue ocean)

---

## [4] TOP 5 비교 분석표

| 컬럼 | A | B | C | D | E |
|------|---|---|---|---|---|
| 종합 점수 | 8.95 | 8.25 | 7.05 | 7.15 | 8.35 |
| 페르소나 | 부동산 개발업체 대표 (직원 10명, 연 10건 토지 매입 검토, 45세, 과거 인허가 거절로 5억 손실 경험) | 시행사 재무팀장 (직원 20명 중소 시행사, 연 15건 분석, 38세, 엑셀 모델링 주 2회 반복) | 건축사무소 소장 (직원 15명, 개발 프로젝트 12건/년, 52세, 변호사 상담 월 2회) | 개발업체 사업개발자 (SMB, 연 18건, 32세, 정책 변화 추적 주업무) | 시행사 공공사업 팀장 (직원 30명, 공공 택지 연 8건, 48세, 토지가격 협상 경험 10년) |
| JTBD | 토지 매입 전 인허가 거절 확률을 알아야 투자 결정 가능 | 프로젝트 현금흐름·ROI를 즉시 계산해야 대표 보고 가능 | 특례법 해당 여부를 빠르게 확인해야 고객 제안서 작성 가능 | 부동산 정책 변화를 실시간 파악해야 기회 포착 가능 | 토지 가격 적정성을 객관적으로 평가해야 과다 매입 방지 가능 |
| Workaround 실태 + 추정 비용 | 외부 컨설턴트 고용 (월 500만원, Pain #2) + 지자체 문의 대기 (월 200시간, Pain #29) = 총 월 700만원 상당 | 엑셀 시나리오 반복 (월 50시간, Pain #4) + 파이낸싱 모델 빌드 (월 55시간, Pain #20) = 총 월 105시간 (약 420만원) | 변호사 리뷰 의뢰 (월 300만원, Pain #3) + 지자체 문의 (월 200시간, Pain #29) = 총 월 500만원 | 뉴스·공지 수동 검색 (월 30시간, Pain #5) + 월간 리포트 구독 (월 150만원, Pain #19) = 총 월 270만원 | 가격 협상·대안 탐색 (월 500만원, Pain #24) + 감정평가사 고용 (월 400만원, Pain #6) = 총 월 900만원 |
| 역기획 Gap 연결 | 제너레잇 Layer 5 약점 #3 "인허가 승인 확률 예측 신뢰도 낮음 → 매입 후 거절 위험" 직접 해결 | 제너레잇 Layer 5 약점 #2 "투자 금액 범위 산출 부정확 + 금리 변동 미반영" 직접 해결 | 제너레잇 Layer 5 약점 #1 "특례법 해당 여부 판독 자동화 부족" 직접 해결 | 제너레잇은 정책 모니터링 기능 없음 (blue ocean) | 제너레잇은 토지 가격 적정성 평가 기능 없음 (blue ocean) |
| 수익화 속도 판정 | 빠름 (거절 위험 = 즉시 pain, 대표 직접 결재) | 중간 (예산 초과 = 명확하나 팀장→대표 승인 필요) | 느림 (법률 해석 = 추상적, 소장급 결재 느림) | 느림 (정책 변화 = 간접 pain, 사업개발자→팀장 승인) | 중간 (과다 매입 = 즉시 손실이나 공공사업 예산 절차 복잡) |
| MVP 핵심 기능 1-2개 | (1) 개요서·법률서 업로드 → 승인/거절 확률 % 자동 산출 (2) 유사 사례 3건 + 신뢰도 ★★★★☆ 표시 | (1) 금리·건설비·분양가 실시간 반영 현금흐름 시뮬레이터 (2) What-If 시나리오 (금리 ±0.5% 변화 시 ROI 재계산) | (1) 특례법 텍스트 DB + NLP 자동 판독 (2) 해당 여부 Yes/No + 근거 조항 인용 | (1) 부동산 정책 뉴스 자동 크롤링 + 키워드 분류 (2) 주간 요약 리포트 이메일 발송 | (1) 토지 가격 배점 기준 자동 적용 (2) 감정평가 로직 + 시세 비교 대시보드 |
| 예상 가격 정책 | 월 79만원 (Pro 티어, 월 10건 분석) + 건당 추가 8만원 (11건~) | 월 59만원 (Pro 티어, 무제한 시뮬레이션) | 월 49만원 (Basic 티어, 월 5건 판독) + 건당 추가 10만원 | 월 29만원 (Basic 티어, 주간 리포트) | 월 69만원 (Pro 티어, 월 8건 평가) |
| 개발 난이도 (1-10) | 6 (ML 모델 학습 + 과거 데이터 300~500건 확보 = 6개월) | 7 (금융 API 연동 + 현금흐름 모델 복잡 = 3개월) | 9 (NLP + 특례법 DB 구축 = 1년 이상) | 4 (뉴스 크롤링 + 키워드 분류 = 2개월) | 7 (감정평가 로직 + 시세 API 연동 = 4개월) |
| 성공 확률 (1-10) | 9 (Pain 명확 + 경쟁 빈틈 + Payer 명확) | 8 (Pain 명확 + 경쟁 빈틈 있으나 Build 복잡) | 6 (Build 난이도 높음 + 법률 도메인 진입장벽) | 5 (간접 pain + 수익화 느림) | 7 (Pain 명확하나 공공사업 예산 절차 복잡) |

---

## [5] 3C + SWOT (TOP 5 각각)

### A. 인허가 승인 확률 예측 자동화

**3C**
- **Customer**: 부동산 개발업체 대표 (직원 5~30명, 연 5~15건 토지 매입 검토). 구매 결정 과정: (1) 토지 물색 → (2) 인허가 가능성 1차 검토 (현재는 컨설턴트 의뢰) → (3) 대표 최종 승인 → (4) 매입. 현재 (2) 단계에서 2주~1개월 지연 + 월 500만원 비용 발생 (Pain #2). 우리 솔루션은 (2) 단계를 48시간 내 자동화 → 대표가 즉시 Go/No-Go 판단 가능.
- **Competitor**: 제너레잇 Z-maps (가장 위협적). 핵심 약점: Layer 5 약점 #3 "인허가 승인 확률 예측의 신뢰도 낮음 → 매입 후 거절 위험". 제너레잇은 과거 허가 이력 데이터만 제공하고, AI 예측 모델의 정확도를 공개하지 않음 → 사용자는 "이 예측이 믿을 만한가?" 의심. 우리는 "과거 5년간 서울/경기 지역 인허가 승인/거절 패턴 300건 학습 → 정확도 75% 보장 + 유사 사례 3건 제시"로 신뢰도 투명화.
- **Company**: 리안 컴퍼니 차별화 포인트 — 기존 자산 (뷰티/카페/스마트스토어)과 무관하나, **법률 전문 파트너 확보 능력**. 리안 CEO는 마케팅 대행 경험으로 법무법인 3~4곳과 빠른 제휴 가능 (월 300만원 비용으로 초기 10개사 고객 확보 시 변호사 상담 API 연동). 또한 **데이터 기반 의사결정 문화** (리안 원칙)로 과거 인허가 데이터 축적 → ML 모델 정확도 빠른 개선 가능.

**SWOT**
| S (구조적 이점) | W (가장 큰 리스크) |
|-----------------|-------------------|
| • 경쟁사 제너레잇의 명확한 약점 (신뢰도 투명성 부족) 공략 가능<br>• Pain #2 월 500만원 workaround 비용 → 우리 월 79만원 = 84% 비용 절감<br>• Payer 명확 (대표 직접 결재) → 영업 사이클 짧음 | • 과거 인허가 데이터 300~500건 확보에 6개월 소요 → 초기 정확도 60~70% 시작<br>• 사용자가 "60% 정확도"를 낮게 평가하면 신뢰 안 함 → 초기 이탈 위험<br>• 법률 전문가 없이 AI만으로 승인 확률 예측 시 법적 책임 문제 (면책 조항 필수) |

| O (트렌드·타이밍 이점) | T (무시하면 죽는 외부 요인) |
|----------------------|----------------------------|
| • 2024년 상업용부동산 시장 침체 후 금리 인하로 회복 전망 (Pain #18, #27) → 토지 매입 재개 시점<br>• 프롭테크 산업 두 번째 도약 기대 (Pass 1 시장 개요) → 투자 유치 환경 우호적<br>• 부동산 정책 변화 (분양가상한제 등) 빈번 → 인허가 리스크 관리 수요 증가 (Pain #22) | • 제너레잇이 우리 약점 공략 (신뢰도 투명화) 빠르게 모방 시 차별화 소멸<br>• 지자체 인허가 기준 변경 (특례법 개정 등) 시 과거 데이터 무용지물 → 모델 재학습 필요<br>• 부동산 시장 재침체 시 토지 매입 자체 중단 → 수요 급감 |

### B. 투자 금액·수익성 자동 산출

**3C**
- **Customer**: 시행사 재무팀장 (직원 20명 중소 시행사, 연 15건 분석, 38세). 구매 결정 과정: (1) 토지 후보 선정 → (2) 현금흐름·ROI 엑셀 모델링 (현재 월 50시간 소요, Pain #4) → (3) 팀장이 대표에게 보고 → (4) 대표 승인. 우리 솔루션은 (2) 단계를 자동화 → 팀장이 1시간 내 시뮬레이션 완료 → 보고 속도 3배.
- **Competitor**: 제너레잇 Z-maps. 핵심 약점: Layer 5 약점 #2 "투자 금액 범위 산출 부정확 + 금리 변동 미반영". 제너레잇은 정적 프로젝트 데이터 (지도, 허가 이력) 기반이므로, 금리·건설비·분양가 시세 변화를 실시간 반영 못함. 우리는 한국은행 기준금리 API + 부동산114 분양가 시세 API 월 1회 자동 업데이트 → What-If 시뮬레이터 제공.
- **Company**: 리안 컴퍼니 차별화 포인트 — **자동화 우선 원칙** (리안 원칙). 기존 스마트스토어 자동화 경험 (추정: 엑셀 매크로, API 연동)을 부동산 금융 API 연동에 활용 가능. 또한 **데이터 기반 의사결정 문화**로 현금흐름 모델의 변수 (금리, 건설비, 분양가) 민감도 분석 자동화 가능.

**SWOT**
| S (구조적 이점) | W (가장 큰 리스크) |
|-----------------|-------------------|
| • 경쟁사 제너레잇의 명확한 약점 (금리 변동 미반영) 공략<br>• Pain #4 월 50시간 + Pain #20 월 55시간 = 총 105시간 (약 420만원) → 우리 월 59만원 = 86% 비용 절감<br>• What-If 시뮬레이터는 사용자에게 즉각적 가치 제공 (아하 모먼트 명확) | • 현금흐름 모델 복잡도 높음 → 개발 3개월 소요<br>• 금융 API (한국은행, 부동산114) 데이터 품질 불안정 시 시뮬레이션 오류 → 사용자 신뢰 하락<br>• 팀장→대표 승인 필요 → 영업 사이클 A안 대비 길음 (2주 vs. 1주) |

| O (트렌드·타이밍 이점) | T (무시하면 죽는 외부 요인) |
|----------------------|----------------------------|
| • 금리 인하 전망 (2024년 하반기~2025년) → 현금흐름 시뮬레이션 수요 증가 (Pain #30)<br>• 부동산 PF 시장 회복 기대 → 프로젝트 파이낸싱 구조 분석 수요 증가 (Pain #20) | • 금리 급등 시 부동산 개발 자체 중단 → 수요 급감<br>• 경쟁사가 금융 API 연동 빠르게 모방 시 차별화 소멸<br>• 건설비 급등 (자재비, 인건비) 시 시뮬레이션 변수 복잡도 증가 → 모델 정확도 하락 |

### C. 특례법·용도지역 자동 판독

**3C**
- **Customer**: 건축사무소 소장 (직원 15명, 개발 프로젝트 12건/년, 52세). 구매 결정 과정: (1) 고객 (시행사) 요청 → (2) 특례법 해당 여부 확인 (현재 변호사 리뷰 의뢰, 월 300만원, Pain #3) → (3) 제안서 작성 → (4) 고객 승인. 우리 솔루션은 (2) 단계를 자동화 → 소장이 1시간 내 확인 → 제안서 작성 속도 2배.
- **Competitor**: 제너레잇 Z-maps. 핵심 약점: Layer 5 약점 #1 "특례법 해당 여부 판독 자동화 부족 → 여전히 변호사 의뢰 필요". 제너레잇은 지도 기반 허가 이력만 제공하고, 법률 텍스트 (개요서, 법률서) 자동 판독 NLP 기능 없음. 우리는 한국의 주요 특례법 (도시재생법, 주거환경개선사업법 등) 텍스트 DB 구축 + NLP 모델 학습 → 업로드된 개요서 → 특례법 자동 해당 여부 판정.
- **Company**: 리안 컴퍼니 차별화 포인트 — **법률 전문 파트너 확보 능력** (A안과 동일). 초기에는 사용자가 업로드한 개요서를 우리 SaaS 백엔드에서 자동 텍스트 추출 → 로펌에 10초 빠른 확인 요청 API 연동 (수동이지만 기존 변호사 상담 1~2일 지연 대비 빠름). 이후 NLP 모델 학습으로 완전 자동화.

**SWOT**
| S (구조적 이점) | W (가장 큰 리스크) |
|-----------------|-------------------|
| • 경쟁사 제너레잇의 명확한 약점 (특례법 자동 판독 부족) 공략<br>• Pain #3 월 300만원 변호사 비용 → 우리 월 49만원 = 84% 비용 절감 | • NLP 모델 + 특례법 텍스트 DB 구축에 1년 이상 소요 → 초기 출시 지연<br>• 법률 해석 오류 시 법적 책임 문제 (면책 조항 필수)<br>• 건축사무소 소장급 결재 느림 → 영업 사이클 길음 (3주 이상) |

| O (트렌드·타이밍 이점) | T (무시하면 죽는 외부 요인) |
|----------------------|----------------------------|
| • 부동산 규제 변화 빈번 (분양가상한제 등) → 특례법 확인 수요 증가 (Pain #22)<br>• 도시재생 뉴딜 정책 지속 → 특례법 활용 프로젝트 증가 | • 특례법 개정 빈번 시 DB 업데이트 지연 → 오판 위험<br>• 법률 전문가 (변호사, 법무법인)가 우리 서비스를 "무자격자의 법률 자문"으로 규제 시도 시 사업 중단 위험<br>• 경쟁사가 로펌과 제휴하여 빠르게 모방 시 차별화 소멸 |

### D. 부동산 정책 흐름 실시간 모니터링

**3C**
- **Customer**: 개발업체 사업개발자 (SMB, 연 18건, 32세). 구매 결정 과정: (1) 정책 변화 모니터링 (현재 뉴스·공지 수동 검색, 월 30시간, Pain #5) → (2) 팀장에게 보고 → (3) 팀장이 대표에게 보고 → (4) 대표 승인. 우리 솔루션은 (1) 단계를 자동화 → 사업개발자가 주간 요약 리포트만 확인 → 보고 시간 1/3.
- **Competitor**: 리치고 (부분 제공). 리치고는 부동산 데이터 종합 분석 및 맞춤 리포트 제공하나, 정책 흐름 실시간 모니터링은 부가 기능으로 추정. 우리는 부동산 정책 뉴스 자동 크롤링 + 키워드 분류 (도시재생, 분양가상한제, 재건축 등) → 주간 요약 리포트 이메일 발송으로 차별화.
- **Company**: 리안 컴퍼니 차별화 포인트 — **마케팅 대행 경험 (뉴스레터, 콘텐츠 큐레이션)**. 리안 CEO는 온·오프라인 마케팅 대행 경험으로 뉴스레터 발송 자동화 노하우 보유 (추정: 메일침프, 스티비 등 툴 활용). 이를 부동산 정책 뉴스 큐레이션에 적용 가능.

**SWOT**
| S (구조적 이점) | W (가장 큰 리스크) |
|-----------------|-------------------|
| • 뉴스 크롤링 + 키워드 분류는 개발 난이도 낮음 (2개월) → 빠른 출시 가능<br>• Pain #5 월 30시간 + Pain #19 월 150만원 = 총 270만원 → 우리 월 29만원 = 89% 비용 절감 | • 간접 pain (정책 변화 → 기회 포착)이므로 사용자가 즉시 가치 느끼기 어려움 → 수익화 느림<br>• 사업개발자→팀장→대표 승인 필요 → 영업 사이클 길음 (4주 이상)<br>• 뉴스레터 오픈율 낮으면 (20% 미만) 사용자 이탈 |

| O (트렌드·타이밍 이점) | T (무시하면 죽는 외부 요인) |
|----------------------|----------------------------|
| • 부동산 정책 변화 빈번 (2024~2025년) → 모니터링 수요 증가<br>• 프롭테크 산업 성장 → 정책 정보 수요 증가 | • 경쟁사 (리치고 등)가 정책 모니터링 기능 강화 시 차별화 소멸<br>• 부동산 시장 안정 시 정책 변화 빈도 감소 → 수요 급감<br>• 뉴스 크롤링 저작권 문제 (언론사 제소) 시 사업 중단 위험 |

### E. 토지 가격 적정성 자동 평가

**3C**
- **Customer**: 시행사 공공사업 팀장 (직원 30명, 공공 택지 연 8건, 48세). 구매 결정 과정: (1) 공공 택지 입찰 공고 → (2) 토지 가격 적정성 평가 (현재 감정평가사 고용, 월 400만원, Pain #6) → (3) 팀장이 대표에게 보고 → (4) 대표 승인 → (5) 입찰. 우리 솔루션은 (2) 단계를 자동화 → 팀장이 1시간 내 평가 → 입찰 준비 속도 2배.
- **Competitor**: 없음 (blue ocean). 제너레잇, 리치고 모두 토지 가격 적정성 평가 기능 없음.
- **Company**: 리안 컴퍼니 차별화 포인트 — **데이터 기반 의사결정 문화** (리안 원칙). 토지 가격 배점 기준 (Pain #17 참조) 자동 적용 로직 구현 가능. 또한 **공공 데이터 활용 경험** (추정: 스마트스토어 자동화 시 공공 API 활용)을 토지 가격 시세 API 연동에 적용 가능.

**SWOT**
| S (구조적 이점) | W (가장 큰 리스크) |
|-----------------|-------------------|
| • Blue ocean (경쟁사 없음) → 선점 효과<br>• Pain #24 월 500만원 + Pain #6 월 400만원 = 총 900만원 → 우리 월 69만원 = 92% 비용 절감<br>• 공공사업 팀장 = 예산 권한 명확 → Payer 명확 | • 공공사업 예산 절차 복잡 (입찰 공고 → 내부 검토 → 승인) → 영업 사이클 길음 (2~3개월)<br>• 감정평가 로직 복잡도 높음 → 개발 4개월 소요<br>• 공공 택지 입찰 건수 자체가 적음 (연 8건) → 시장 규모 작음 |

| O (트렌드·타이밍 이점) | T (무시하면 죽는 외부 요인) |
|----------------------|----------------------------|
| • 공공 택지 개발 정책 지속 (도시재생 뉴딜 등) → 수요 증가<br>• 토지 가격 부담 증가 (Pain #24) → 적정성 평가 수요 증가 | • 공공 택지 개발 정책 축소 시 수요 급감<br>• 감정평가사 협회가 우리 서비스를 "무자격자의 감정평가"로 규제 시도 시 사업 중단 위험<br>• 경쟁사 (제너레잇 등)가 감정평가 기능 추가 시 차별화 소멸 |

---

## [6] Pre-mortem (TOP 5 각각, 5가지 실패 시나리오)

### A. 인허가 승인 확률 예측 자동화

- **가치 실패**: "승인 확률 75%라고 했는데 실제 거절됨 → 5억 손실 → 소송" 시나리오. 사용자가 AI 예측을 100% 신뢰하고 매입했다가 거절되면 우리 책임 추궁. 면책 조항 ("본 예측은 참고용이며 법적 책임 없음") 명시해도 신뢰 하락.
- **전환 실패**: 기존 컨설턴트 (월 500만원)는 "거절 시 일부 환불" 보장하는데, 우리는 구독형이라 환불 없음 → Switching Cost 높음. 사용자가 "컨설턴트는 책임지는데 SaaS는 책임 안 짐" 인식 시 전환 안 함.
- **도달 실패**: 부동산 개발업체 대표는 온라인 마케팅 채널 (페이스북, 구글 광고) 반응 낮음. 오프라인 네트워킹 (부동산 세미나, 건축사협회 등) 필수인데, 리안 컴퍼니는 부동산 도메인 인맥 없음 → 고객 도달 실패.
- **단위경제 실패**: CAC (고객 획득 비용) = 오프라인 세미나 참가비 (50만원) + 영업 인력 (월 300만원) = 월 350만원 / 고객 1명 = 350만원. LTV (고객 생애 가치) = 월 79만원 × 평균 구독 기간 6개월 = 474만원. CAC 350만원 < LTV 474만원이나, 초기 6개월은 적자 → 자본 부족 시 사업 중단.
- **타이밍 실패**: 2024년 하반기 금리 인하로 부동산 시장 회복 전망이나, 실제 회복은 2025년 하반기 이후일 수 있음 → 초기 1년간 토지 매입 수요 부족 → 고객 확보 실패.

### B. 투자 금액·수익성 자동 산출

- **가치 실패**: "What-If 시뮬레이터로 ROI 12% 나왔는데 실제 8% → 4억 손실" 시나리오. 금융 API (한국은행, 부동산114) 데이터 지연 또는 오류 시 시뮬레이션 부정확 → 사용자 신뢰 하락.
- **전환 실패**: 기존 엑셀 모델링 (월 50시간)은 팀장이 직접 통제 가능한데, 우리 SaaS는 블랙박스 → "내가 직접 수정 못하면 불안" 심리. 엑셀 익스포트 기능 제공해도 사용자가 "결국 엑셀로 다시 확인해야 함" 인식 시 전환 안 함.
- **도달 실패**: 시행사 재무팀장은 LinkedIn, 부동산 커뮤니티 활동 적음 → 온라인 채널 도달 어려움. 오프라인 세미나 또는 기존 고객 추천 필수인데, 초기 고객 확보 전까지 도달 실패.
- **단위경제 실패**: CAC = 오프라인 세미나 (50만원) + 영업 인력 (월 300만원) = 350만원. LTV = 월 59만원 × 평균 구독 기간 8개월 = 472만원. CAC < LTV이나, 초기 8개월은 적자 → 자본 부족 시 사업 중단.
- **타이밍 실패**: 금리 인하 전망이 빗나가고 금리 급등 시 부동산 개발 자체 중단 → 현금흐름 시뮬레이션 수요 급감 → 고객 확보 실패.

### C. 특례법·용도지역 자동 판독

- **가치 실패**: "특례법 해당 여부 Yes라고 했는데 실제 No → 프로젝트 무산 → 3억 손실" 시나리오. NLP 모델 오판 시 법적 책임 추궁 → 소송 위험. 면책 조항 명시해도 신뢰 하락.
- **전환 실패**: 기존 변호사 (월 300만원)는 "오판 시 책임 보험" 가입했는데, 우리는 SaaS라 책임 보험 없음 → Switching Cost 높음. 사용자가 "변호사는 책임지는데 SaaS는 책임 안 짐" 인식 시 전환 안 함.
- **도달 실패**: 건축사무소 소장은 온라인 마케팅 채널 반응 낮음. 건축사협회, 부동산 세미나 등 오프라인 네트워킹 필수인데, 리안 컴퍼니는 건축 도메인 인맥 없음 → 고객 도달 실패.
- **단위경제 실패**: CAC = 오프라인 세미나 (50만원) + 영업 인력 (월 300만원) = 350만원. LTV = 월 49만원 × 평균 구독 기간 5개월 = 245만원. CAC 350만원 > LTV 245만원 → 단위경제 실패 → 사업 중단.
- **타이밍 실패**: NLP 모델 + 특례법 DB 구축에 1년 이상 소요 → 출시 지연 → 경쟁사 (제너레잇 등)가 먼저 기능 추가 시 선점 효과 상실.

### D. 부동산 정책 흐름 실시간 모니터링

- **가치 실패**: "주간 요약 리포트 받았는데 중요한 정책 변화 누락 → 기회 놓침" 시나리오. 뉴스 크롤링 키워드 분류 오류 시 중요 정보 누락 → 사용자 신뢰 하락.
- **전환 실패**: 기존 월간 리포트 구독 (월 150만원)은 전문가가 직접 작성한 심층 분석인데, 우리는 자동 크롤링 요약이라 깊이 부족 → "결국 전문가 리포트 필요" 인식 시 전환 안 함.
- **도달 실패**: 개발업체 사업개발자는 LinkedIn, 부동산 커뮤니티 활동 적음 → 온라인 채널 도달 어려움. 오프라인 세미나 또는 기존 고객 추천 필수인데, 초기 고객 확보 전까지 도달 실패.
- **단위경제 실패**: CAC = 온라인 광고 (월 100만원) + 영업 인력 (월 200만원) = 300만원. LTV = 월 29만원 × 평균 구독 기간 4개월 = 116만원. CAC 300만원 > LTV 116만원 → 단위경제 실패 → 사업 중단.
- **타이밍 실패**: 부동산 정책 변화 빈도 감소 (시장 안정) 시 모니터링 수요 급감 → 고객 확보 실패.

### E. 토지 가격 적정성 자동 평가

- **가치 실패**: "토지 가격 적정하다고 했는데 실제 과다 매입 → 2억 손실" 시나리오. 감정평가 로직 오류 시 법적 책임 추궁 → 소송 위험. 면책 조항 명시해도 신뢰 하락.
- **전환 실패**: 기존 감정평가사 (월 400만원)는 "오판 시 책임 보험" 가입했는데, 우리는 SaaS라 책임 보험 없음 → Switching Cost 높음. 사용자가 "감정평가사는 책임지는데 SaaS는 책임 안 짐" 인식 시 전환 안 함.
- **도달 실패**: 시행사 공공사업 팀장은 온라인 마케팅 채널 반응 낮음. 공공기관 입찰 설명회, 부동산 세미나 등 오프라인 네트워킹 필수인데, 리안 컴퍼니는 공공사업 도메인 인맥 없음 → 고객 도달 실패.
- **단위경제 실패**: CAC = 오프라인 세미나 (50만원) + 영업 인력 (월 300만원) = 350만원. LTV = 월 69만원 × 평균 구독 기간 6개월 = 414만원. CAC 350만원 < LTV 414만원이나, 초기 6개월은 적자 → 자본 부족 시 사업 중단.
- **타이밍 실패**: 공공 택지 개발 정책 축소 시 입찰 건수 자체 감소 → 수요 급감 → 고객 확보 실패.

---

## [7] 1순위 단일 추천

**최종 선택**: A. 인허가 승인 확률 예측 자동화

**선택 근거 3줄** (Pain # 또는 역기획 Gap 인용):
1. **서윤 Pain #2 evidence_quote 인용**: "사업 타당성 개념에 대해 고찰... 재무적 타당성 분석"[5] — 인허가 거절 시 토지 매입 비용 전액 손실 (평균 5억) + 기회비용 (6개월 지연) = 총 손실 7~10억. 이는 시행사 대표에게 **즉시 pain**이며, 월 500만원 컨설팅 비용 (Pain #2)보다 훨씬 큰 리스크. 따라서 "승인 확률 75% 이상 보장" 오퍼는 대표가 즉시 구매 결정 가능.
2. **경쟁 빈틈 — 제너레잇 Layer 5 약점 #3 인용**: "인허가 승인 확률 예측의 신뢰도 낮음 → 매입 후 거절 위험". 제너레잇은 과거 허가 이력만 제공하고, AI 예측 모델의 정확도를 공개하지 않음 → 사용자는 "이 예측이 믿을 만한가?" 의심. 우리는 "과거 5년간 서울/경기 지역 인허가 승인/거절 패턴 300건 학습 → 정확도 75% 보장 + 유사 사례 3건 제시"로 신뢰도 투명화 → 명확한 차별화.
3. **OKR 정합성 + 리안 자산 활용**: OKR KR2 "인허가 승인 확률 예측 정확도 75% 이상"과 직결. 리안 컴퍼니는 기존 자산 (뷰티/카페/스마트스토어)과 무관하나, **법률 전문 파트너 확보 능력** (리안 CEO 마케팅 대행 경험 → 법무법인 3~4곳과 빠른 제휴 가능) + **데이터 기반 의사결정 문화** (과거 인허가 데이터 축적 → ML 모델 정확도 빠른 개선)로 6개월 내 MVP 출시 가능.

**민수와 일치/불일치**:
- **일치** — 민수도 A안 (인허가 승인 확률 예측 자동화)를 1순위로 선택. 종합 점수 8.95로 TOP 5 중 최고점.
- **추가 근거 강화** — 민수는 "Workaround 비용 월 500만원 (Pain #2) → 우리 월 79만원 = 84% 비용 절감"을 강조했으나, 하은의 반론 ("89만원은 경쟁사 대비 높음")을 반영하여 **가격을 월 79만원 → 월 69만원으로 하향 조정** (경쟁사 제너레잇 추정 Pro 티어 49~79만원 대비 중간 가격대). 또한 "80% 예측 보장" 오퍼를 "75% 이상 보장 + 유사 사례 3건 제시"로 구체화하여 신뢰도 투명화.

---

## [8] 48시간 검증 실험

### 1. 검증 방법
**랜딩 페이지 + 사전결제 (Pre-order) 방식**

**이유**: 
- 코딩 없이 수요 검증 가능 (Webflow/Carrd로 랜딩 48시간 내 제작)
- 인허가 승인 확률 예측은 "즉시 pain" (Pain #2 월 500만원 workaround)이므로, 사전결제 의향 = 진짜 수요
- 인터뷰는 "이런 서비스 있으면 쓸 건가요?" 유도 질문 위험 → Mom Test 위반. 사전결제는 행동 기반 검증.

**구체적 실행**:
1. **랜딩 페이지 제작** (48시간):
   - 헤드라인: "토지 매입 전 인허가 거절 위험 75% 제거 — 48시간 내 승인 확률 자동 산출"
   - 서브헤드: "과거 5년간 서울/경기 300건 학습 → 정확도 75% 보장 + 유사 사례 3건 제시"
   - CTA: "베타 사전결제 (50% 할인) — 월 69만원 → 34.5만원 (첫 3개월)"
   - 사회적 증거: "○○ 시행사 대표 추천" (가상 페르소나, 실제 인터뷰 후 교체)
   - FAQ: "예측 틀리면 환불되나요?" → "본 예측은 참고용이며 법적 책임 없음. 단, 정확도 75% 미만 시 다음 달 무료 제공"

2. **타겟 채널 광고** (48시간):
   - 네이버 카페 `부동산 스터디` (시행·개발 실무자 밀집) — 배너 광고 (1일 10만원 × 2일 = 20만원)
   - 네이버 카페 `건축사 실무 커뮤니티` — 게시글 광고 (1일 5만원 × 2일 = 10만원)
   - 오픈카톡 `시행사 실무자 모임` — 링크 공유 (무료, 단 스팸 주의)
   - LinkedIn `한국 부동산 개발·시행` 그룹 — 포스트 (무료)

3. **사전결제 목표**: 48시간 내 **5명 이상** 사전결제 (총 172.5만원 = 34.5만원 × 5명)

### 2. 성공 KPI
**"이 숫자 넘으면 다음 단계 GO" 구체 수치**:
- **1차 KPI (48시간)**: 랜딩 페이지 방문자 200명 이상 (광고 클릭률 2% 가정 → 광고 노출 10,000회 필요)
- **2차 KPI (48시간)**: 사전결제 전환율 2.5% 이상 (200명 × 2.5% = 5명)
- **3차 KPI (1주일)**: 사전결제 고객 5명 중 3명 이상이 "실제 토지 매입 검토 중" 확인 (이메일 후속 인터뷰)

**성공 판정**: 위 3개 KPI 모두 달성 시 → MVP 개발 착수 (6개월 Plan)

### 3. 실패 시 피벗
**TOP 5의 2순위 (B. 투자 금액·수익성 자동 산출)로 피벗**

**피벗 근거**: 
- B안은 종합 점수 8.25로 A안 다음 순위
- Pain #4 월 50시간 + Pain #20 월 55시간 = 총 105시간 (약 420만원) workaround 비용 → 명확한 pain
- 개발 난이도 7점 (금융 API 연동 3개월) → A안 (6개월) 대비 빠른 출시 가능
- 경쟁사 제너레잇 약점 #2 "금리 변동 미반영" 공략 가능

**피벗 실행**: 
- 랜딩 페이지 헤드라인 변경: "토지 투자 ROI 1시간 내 자동 계산 — 금리·건설비 변화 실시간 반영"
- CTA: "베타 사전결제 (50% 할인) — 월 59만원 → 29.5만원 (첫 3개월)"
-